---
- name: Spinup RHPDS AWS Blank Enviornment
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files: 
    - vars.yml

  tasks:
    - name: Destroy OCP4 Cluster
      import_role:
        name: destroy-ocp4-cluster
