---
- name: Spinup RHPDS AWS Blank Enviornment
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files: 
    - vars.yml

  tasks:
    - name: Order AWS Open Environment
      import_role:
        name: order-aws-oe

    - name: Get AWS Creds
      import_role:
        name: get-aws-creds
